
def nom_entity(entity:int):    
 if entity == 1: return 'AGUASCALIENTES'
 if entity == 2: return 'BAJA CALIFORNIA'
 if entity == 3: return 'BAJA CALIFORNIA SUR'
 if entity == 4: return 'CAMPECHE'
 if entity == 5: return 'COAHUILA DE ZARAGOZA'
 if entity == 6: return 'COLIMA'
 if entity == 7: return 'CHIAPAS'
 if entity == 8: return 'CHIHUAHUA'
 if entity == 9: return 'CUIDAD DE MEXICO'
 if entity == 10: return 'DURANGO'
 if entity == 11: return 'GUANAJUATO'
 if entity == 12: return 'GUERRERO'
 if entity == 13: return 'HIDALGO'
 if entity == 14: return 'JALISCO'
 if entity == 15: return 'MEXICO'
 if entity == 16: return 'MICHOACAN DE OCAMPO'
 if entity == 17: return 'MORELOS'
 if entity == 18: return 'NAYARIT'
 if entity == 19: return 'NUEVO LEON'
 if entity == 20: return 'OAXACA'
 if entity == 21: return 'PUEBLA'
 if entity == 22: return 'QUERETARO DE ARTEAGA'
 if entity == 23: return 'QUINTANA ROO'
 if entity == 24: return 'SAN LUIS POTOSI'
 if entity == 25: return 'SINALOA'
 if entity == 26: return 'SONORA'
 if entity == 27: return 'TABASCO'
 if entity == 28: return 'TAMAULIPAS'
 if entity == 29: return 'TLAXCALA'
 if entity == 30: return 'VERACRUZ DE IGNACIO DE LA LLAVE'
 if entity == 31: return 'YUCATAN'
 if entity == 32: return 'ZACATECAS'

